### ISSUE TITLE
Not able to run ajenti-dev-multitool --rebuild in demo plugins

### ISSUE THREAD

**Issue by jeemeekay** [ajenti/demo-plugins#3]
Hello all,
I am new to ajenti 2 plugin development. I am trying to run the command below
`ajenti-dev-multitool --rebuild` for the demo plugins and I consistently see the error below across all of them
```
Traceback (most recent call last):
  File "/usr/local/bin/ajenti-dev-multitool", line 655, in <module>
    run_build(plugin, False)
  File "/usr/local/bin/ajenti-dev-multitool", line 95, in run_build
    resources = yaml.load(open(os.path.join(plugin, 'plugin.yml')), Loader=yaml.SafeLoader)['resources']
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 408, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 129, in construct_sequence
    return [self.construct_object(child, deep=deep)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 129, in <listcomp>
    return [self.construct_object(child, deep=deep)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object:aj.plugins.PluginDependency'
  in "./plugin.yml", line 9, column 7
```
I am running this on Ubuntu 22.04 python 3.10.6. Any help would be appreciated @Eugeny @kiarn @mathieu-aubin

**Comment by kiarn** [comment]
Hello @jeemeekay 

This is done in the last PR : https://github.com/ajenti/demo-plugins/pull/4

@Eugeny : can you please merge it ? Thanks !

@jeemeekay : just ask if you have questions :)

Arnaud

**Comment by jeemeekay** [comment]
Thanks so much @kiarn . I eventually figured out the issue and was literally about to raise a PR and just saw you had responded and merged a fix. Well done for the work guys and @Eugeny not sure if you remember me but I used to reach out to you back in the days of Ajenti 1. I'm back doing ajenti again and trying to migrate the project I worked on at the time to ajenti 2, so will probably reach out if any questions if thats okay?

**Comment by kiarn** [comment]
Sure it's ok ! But actually @Eugeny works on other projects, I maintain Ajenti 2.
Just ask if you need anything !

**Comment by jeemeekay** [comment]
@kiarn Thanks. I guess I have 2 initial questions:
-  is it possible to add another category other than the defaults ['System', 'Tools', 'General', 'Software','Other']?
-  Once I'm done creating a plugin, can I drop it in the /var/lib/ajenti/plugins directory (We used to be able to do this in ajenti 1.x and it would work)?
Thanks again for the prompt response.

**Comment by kiarn** [comment]
> * is it possible to add another category other than the defaults ['System', 'Tools', 'General', 'Software','Other']?

Yes, just use the parameter `attach` in `main.py` for this : 

```
@component(SidebarItemProvider)
class ItemProvider(SidebarItemProvider):
    def __init__(self, context):
        self.context = context

    def provide(self):
        return [
            {
                'attach': 'category:my_own_category',
               ...
            },
```

> * Once I'm done creating a plugin, can I drop it in the /var/lib/ajenti/plugins directory (We used to be able to do this in ajenti 1.x and it would work)?

I'm not sure I understood the question correctly, but I try to answer it : you can use your own directory for all plugins, and then give this directory path as parameter to `ajenti-panel`. If your plugins are located in `/srv/dev/myproject`, then you can do the following:

```
ajenti-panel --stock-plugins --plugins /srv/dev/myproject
```

This will load your own plugins at start.

Arnaud

**Comment by jeemeekay** [comment]
Hi,
I gave this a try and I seeing the below error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aj/api/endpoint.py", line 77, in wrapper
    result = fx(self, context, *args, **kwargs)
![Screenshot 2023-02-18 at 13 33 59](https://user-images.githubusercontent.com/6360592/219868736-a4220898-7404-4940-849a-fdebfcde51cf.png)

  File "/usr/local/lib/python3.10/dist-packages/ajenti_plugin_core/views/api.py", line 236, in handle_api_sidebar
    'sidebar': Sidebar.get(self.context).build(),
  File "/usr/local/lib/python3.10/dist-packages/ajenti_plugin_core/api/sidebar.py", line 68, in build
    raise Exception(f'Attachment point not found: {item["attach"]}')
Exception: Attachment point not found: category:vms
```

See attachment as well. As always the help is much appreciated.

**Comment by jeemeekay** [comment]
![Screenshot 2023-02-18 at 13 33 59](https://user-images.githubusercontent.com/6360592/219868775-63f74541-d04c-4abd-a4f6-815a7ab573ae.png)

**Comment by kiarn** [comment]
Yes, my bad, because the informations were incomplete, sorry for this.

`attach` will attach the link to an existing category, and you need to first create this category like this:

```
    def provide(self):
        return [
            {
                'attach': None,
                'id': 'category:vms',
                'name': _('My Category'),
                'children': [
                ]
            },
```

Arnaud

**Comment by jeemeekay** [comment]
Hi @kiarn ,
Still not working with the latest changes show below. It's not showing any error but it seems its not attaching to the new  category 'vms'

```
def provide(self):
        return [
            {
                # category:tools, category:sofware, category:system, category:other
                'attach': None,
                'id': 'category:vms',
                'name': _('Conference'),
                # https://fontawesome.com/icons/
                'icon': 'question',
                'url': '/view/my_plugin',
                'children': []
            }
        ]

```

**Comment by kiarn** [comment]
Try this:


 ```
def provide(self):
        return [
            {
                'attach': None,
                'id': 'category:vms',
                'name': _('Conference'),
                'children': []
            },
           {
                'attach': 'category:vms',
                'name': _('MyName'),
                'icon': 'question',
                'url': '/view/my_plugin',
                'children': []
           },
        ]
```

Arnaud

**Comment by jeemeekay** [comment]
Hi @kiarn,
That definitely worked. Thanks

**Comment by Eugeny** [comment]
@jeemeekay sorry - it's been too long :D but I'm happy to see Ajenti picking up steam again! As Arnaud said, he's now even more "in the know" on the project than I am :v:

**Comment by jeemeekay** [comment]
@kiarn I'm still having the issue below:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aj/api/endpoint.py", line 77, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ajenti_plugin_core/views/api.py", line 236, in handle_api_sidebar
    'sidebar': Sidebar.get(self.context).build(),
  File "/usr/local/lib/python3.10/dist-packages/ajenti_plugin_core/api/sidebar.py", line 68, in build
    raise Exception(f'Attachment point not found: {item["attach"]}')
Exception: Attachment point not found: category:vms
```
I have created 5 plugins with the code recommendation you sent to me. I have added you to the repo so you can see what I'm doing just in case. 

Thanks

**Comment by kiarn** [comment]
@jeemeekay : you need to declare the category vms only once, e.g. in conference:

```
def provide(self):
       return [
           {
               'attach': None,
               'id': 'category:vms',
               'name': _('Conference'),
               'children': []
           },
       ]
```

Then declare all others plugins dependant from the plugins conference ( in each `plugin.yml` ). Ajenti will automatically resolve the load order and then is the category vms defined when all plugins are loading.

Arnaud

**Comment by jeemeekay** [comment]
@kiarn That actually makes sense (Don't know why I didn't think of it). Yeah it works now. Thanks again :)

**Comment by jeemeekay** [comment]
@kiarn Another question I have, is it possible to access objects in one plugin from another? So for example can I access an object that instantiates 'component' in plugin 'conference' from a separate plugin like 'configure'?

**Comment by kiarn** [comment]
Example:

In `conference/api.py` ( could be `conference/views.py` ) :
```
component = "BLA"
```

In `configure/api.py` ( could be `configure/views.py` ) :
```
from aj.plugins.conference.api import component
print(component) # should print BLA
```

But this method will import component at starts, and it's necessary to check the dependencies in order that the plugin `conference` is imported before the plugin `configure`.

Arnaud

**Comment by jeemeekay** [comment]
@kiarn Hey, its been a minute. I have an issue where there is a plugin I developed but everytime I click the plugin, its always asking for elevation, I have to now enter the user password. Do you know why this would be the case?

**Comment by kiarn** [comment]
Hi, It's hard to say without seeing the code. I assume you are talking about your vms project. Which plugin / sidebar link is concerned ?

**Comment by jeemeekay** [comment]
@kiarn Thanks for the response. You are correct, it is the vms project. The link to the repo is here:
https://github.com/o4jmaster/vms
Let me know if you can access it. The plugin in question is the vmsrouting, everytime I click it on the sidebar, it always asks for elevation.  
What is interesting is, if I change the auth provider to users from os in the ajenti config, I don't see this issue. 

Thanks

**Comment by kiarn** [comment]
If you want to use the users auth provider, please check that the users have the right permissions (in `Ajenti` as root --> Sidebar Users --> Gear near the user).

The permissions should then appear in `/etc/ajenti/users.yml` like:

```
users:
  testuser:
    email: tesuser@my.tld
    permissions: 
      mypermission:read: true
      sidebar:view:/view/myplugin: true
```

In order to use custom permission `mypermission`, you need to define it in `main.py` like [this](https://github.com/ajenti/ajenti/blob/365a59a7b3e488ec4bf63f6713c6cefd8897e30c/plugins/cron/main.py#L23), and to declare it in your view like [this](https://github.com/ajenti/ajenti/blob/365a59a7b3e488ec4bf63f6713c6cefd8897e30c/plugins/cron/views.py#L21).
